url: "https://myquickstart.netlify.app" # the base hostname & protocol for your site, e.g. http://example.com
title: "Blank Jekyll Site" # the name of your site, e.g. ACME Corp.

exclude:
  - netlify.toml
  - README.md
